services:
  laravel-docker:
    container_name: intuji-docker-test
    build: .
    volumes:
      - .:/var/www/html:rw
    ports:
      - "9000:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql_db
      DB_PORT: 3306
      DB_DATABASE: blog
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - mysql_db
  
  mysql_db:
    image: mysql:8.4
    container_name: mysql-container-test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-container-test
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  mysql_data:


    